name: 'Helm Setup'
description: 'Installing helm and setting up kubectl'

inputs:
  CLUSTER_NAME:
    description: 'Name of EKS Cluster'
    required: true
  AWS_REGION:
    description: 'AWS region'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up kubectl
      shell: bash
      run: |
        aws eks update-kubeconfig --name "${{ inputs.CLUSTER_NAME }}" --region ${{ inputs.AWS_REGION }}
        
    - name: Install Helm
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash