apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: java-web-app-hpa
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "webAppLabel" . | indent 4 }}
spec:
  minReplicas: {{ .Values.replica.minReplicas }}
  maxReplicas: {{ .Values.replica.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: java-web-app-deployment
  targetCPUUtilizationPercentage: 50
