---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: java-web-app-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{ include "webAppLabel" . | indent 6 }}